"""F13 Phase A: the offline multi-source blend against the NBP champion.

Plan: ``docs/plans/backlog/FQ_LOSS_RESPONSE_2026-10-04/F13-us-source-ingest_plan_r3.md`` section
"Phase A1 / A" (r3.1, r3.2 and ruling F13-R35 binding). PURE: no network, no clock, no file access,
no Nautilus import. It holds the feature assembly with its leakage assertions, the Student-t blend,
the nested ladder M0' / M1 / M2 / M3, the fold construction, and the paired-delta statistics. The
champion M0 is :func:`breezy.analysis.nbp_calibration.fit_calibration`, left untouched; every CRPS
here goes through :func:`breezy.analysis.nbp_calibration.crps_numerical` with ``center`` = the mu
being scored.

Sealed days. A row whose climate day is on or after ``DEFAULT_SPLITS.holdout_start`` is REFUSED by
every fitting, folding and scoring entry point (:class:`HoldoutLeakError`); this module never calls
``open_holdout``.

Ladder and nesting. The regressors of a cell are the NBP q50, ``obs_so_far`` when defined, then
``L = max(obs_so_far, lamp_rem_max_f)`` (level 1), the PFM mu (level 2) and the GFS MOS mu
(level 3). A row scores with the LONGEST PRESENT PREFIX of [LAMP, PFM, MOS], capped at the model's
level, so a row whose LAMP feature is missing scores exactly as M0' (R35: nothing is imputed). The
level-0 cell is fitted on every row, so M0' is the same fit inside every ladder step.

The distribution is Student-t with ``log sigma = c + d*log(NBP sd)`` (plus ``e*log(source
disagreement)`` only in the separate step ``use_disagreement_sigma``), floored at
``sigma_floor_f``. Weights shrink toward a sum of 1 with ``weight_sum_lambda * n * (sum(w)-1)^2``,
not a hard box. Fitting minimises the Student-t negative log-likelihood; scoring is CRPS.

Module layout (each part < 800 lines; this module is the stable facade scripts and tests import):
``multisource_blend_features`` (inputs, leakage), ``_fit`` (Student-t blend, CRPS), ``_folds``
(folds, out-of-fold scoring), ``_stats`` (paired-delta statistics, acceptance, reporting) and
``_io`` (JSON).
"""

from __future__ import annotations

from breezy.analysis.multisource_blend_features import (
    ARM_NAMES,
    DISAGREEMENT_SD_FLOOR_F,
    HOLDOUT_START,
    HORIZONS,
    LAG_SHIFT_NS,
    LEVEL_SOURCES,
    MISSING_LAMP,
    PEAK_LST_HOURS,
    STRICT_24H_LABEL,
    C1LagEvidenceError,
    FeatureRow,
    FitNotConvergedError,
    HoldoutLeakError,
    InsufficientFoldsError,
    InsufficientRowsError,
    LampFeature,
    LampHour,
    LampRun,
    LeakageError,
    NonFiniteInputError,
    ObsReading,
    PreregIncompleteError,
    SourceVintage,
    assemble_feature_row,
    assert_lamp_run_before_anchor,
    assert_pre_holdout,
    assert_row_leakage_free,
    combined_lamp_input,
    lamp_remaining_feature,
    obs_so_far,
    strict_24h_max_diagnostic,
    validate_percentiles,
)
from breezy.analysis.multisource_blend_fit import (
    SIGMA_FLOOR_SHARPNESS,
    BlendFit,
    BlendSettings,
    CellParams,
    fit_blend,
    floored_sigma,
    intended_level,
    predict_row,
    row_crps,
    score_rows,
    source_disagreement_f,
    student_t_cdf,
)
from breezy.analysis.multisource_blend_folds import (
    ArmPrediction,
    ChampionSpec,
    Fold,
    FoldPlan,
    ScoredRow,
    blend_cdf,
    build_folds,
    champion_cdf,
    days_by_version,
    m0_eligible_plan,
    merge_scored,
    out_of_fold_scores,
    shuffle_labels,
)
from breezy.analysis.multisource_blend_io import (
    feature_row_from_json,
    feature_row_to_json,
    scored_row_from_json,
    scored_row_to_json,
)
from breezy.analysis.multisource_blend_stats import (
    ALPHA_ONE_SIDED,
    AcceptanceDecision,
    AcceptanceInputs,
    DeltaSummary,
    M0PrimeStatus,
    Missingness,
    Verdict,
    complete_case_delta,
    decide_acceptance,
    delta_by_day,
    delta_summary,
    diagnostics,
    fold_mean_crps,
    fold_sd,
    fold_sign_threshold,
    lag_rows_lost,
    lamp_missingness_by_horizon,
    level_counts,
    lower_bound_one_sided,
    m0_prime_status,
    mean_arm_crps,
    mean_arm_difference,
    minimum_effect_floor,
    per_fold_delta,
    per_station_delta,
    require_c1_measured_lags,
    stationary_bootstrap_means,
)

__all__ = [
    "ALPHA_ONE_SIDED",
    "ARM_NAMES",
    "DISAGREEMENT_SD_FLOOR_F",
    "HOLDOUT_START",
    "HORIZONS",
    "LAG_SHIFT_NS",
    "LEVEL_SOURCES",
    "MISSING_LAMP",
    "PEAK_LST_HOURS",
    "SIGMA_FLOOR_SHARPNESS",
    "STRICT_24H_LABEL",
    "AcceptanceDecision",
    "AcceptanceInputs",
    "ArmPrediction",
    "BlendFit",
    "BlendSettings",
    "C1LagEvidenceError",
    "CellParams",
    "ChampionSpec",
    "DeltaSummary",
    "FeatureRow",
    "FitNotConvergedError",
    "Fold",
    "FoldPlan",
    "HoldoutLeakError",
    "InsufficientFoldsError",
    "InsufficientRowsError",
    "LampFeature",
    "LampHour",
    "LampRun",
    "LeakageError",
    "M0PrimeStatus",
    "Missingness",
    "NonFiniteInputError",
    "ObsReading",
    "PreregIncompleteError",
    "ScoredRow",
    "SourceVintage",
    "Verdict",
    "assemble_feature_row",
    "assert_lamp_run_before_anchor",
    "assert_pre_holdout",
    "assert_row_leakage_free",
    "blend_cdf",
    "build_folds",
    "champion_cdf",
    "combined_lamp_input",
    "complete_case_delta",
    "days_by_version",
    "decide_acceptance",
    "delta_by_day",
    "delta_summary",
    "diagnostics",
    "feature_row_from_json",
    "feature_row_to_json",
    "fit_blend",
    "floored_sigma",
    "fold_mean_crps",
    "fold_sd",
    "fold_sign_threshold",
    "intended_level",
    "lag_rows_lost",
    "lamp_missingness_by_horizon",
    "lamp_remaining_feature",
    "level_counts",
    "lower_bound_one_sided",
    "m0_eligible_plan",
    "m0_prime_status",
    "mean_arm_crps",
    "mean_arm_difference",
    "merge_scored",
    "minimum_effect_floor",
    "obs_so_far",
    "out_of_fold_scores",
    "per_fold_delta",
    "per_station_delta",
    "predict_row",
    "require_c1_measured_lags",
    "row_crps",
    "score_rows",
    "scored_row_from_json",
    "scored_row_to_json",
    "shuffle_labels",
    "source_disagreement_f",
    "stationary_bootstrap_means",
    "strict_24h_max_diagnostic",
    "student_t_cdf",
    "validate_percentiles",
]
