"""Import-closure manifest for the code-identity pins (ARCH 4.3). Generated; do not edit.

Regenerate with ``scripts/ci/regen_closure_manifest.py``. Empty at ARCH-0.
"""

from types import MappingProxyType
from typing import Final

CLOSURE_MODULES: Final[MappingProxyType[str, tuple[str, ...]]] = MappingProxyType(
    {
        "breezy.runtime.autonomy_health_cli": (
            "breezy",
            "breezy.persistence",
            "breezy.persistence.autonomy",
            "breezy.persistence.autonomy.canonical",
            "breezy.persistence.autonomy.chain",
            "breezy.persistence.autonomy.closure",
            "breezy.persistence.autonomy.closure_manifest",
            "breezy.persistence.autonomy.detector_catalog",
            "breezy.persistence.autonomy.fold",
            "breezy.persistence.autonomy.fold_pairs",
            "breezy.persistence.autonomy.fold_tallies",
            "breezy.persistence.autonomy.paths",
            "breezy.persistence.autonomy.registry_export",
            "breezy.persistence.autonomy.registry_schema",
            "breezy.persistence.autonomy.rollback_journal",
            "breezy.persistence.autonomy.schemas",
            "breezy.persistence.autonomy.single_read",
            "breezy.persistence.autonomy.verdict",
            "breezy.persistence.autonomy.wire",
            "breezy.registry",
            "breezy.registry.health_model",
            "breezy.registry.sites",
            "breezy.runtime",
            "breezy.runtime.alert_delivery",
            "breezy.runtime.alert_drain",
            "breezy.runtime.alert_outbox",
            "breezy.runtime.alert_proof",
            "breezy.runtime.autonomy_health_cli",
            "breezy.runtime.autonomy_sandbox",
            "breezy.runtime.autonomy_sandbox.binds",
            "breezy.runtime.autonomy_sandbox.bus_handoff",
            "breezy.runtime.autonomy_sandbox.bwrap",
            "breezy.runtime.autonomy_sandbox.interp_links",
            "breezy.runtime.autonomy_sandbox.run_mounts",
            "breezy.runtime.autonomy_sandbox.table",
            "breezy.runtime.health",
            "breezy.runtime.monitor_watch",
            "breezy.runtime.monitor_watch_apply",
            "breezy.runtime.monitor_watch_delivery",
            "breezy.runtime.monitor_watch_deploy",
            "breezy.runtime.monitor_watch_memory",
            "breezy.runtime.monitor_watch_model",
            "breezy.runtime.monitor_watch_producer",
            "breezy.runtime.monitor_watch_timers",
            "breezy.runtime.process_lookup",
            "breezy.runtime.trade_supervisor_core",
            "breezy.runtime.unit_health",
            "breezy.runtime.unit_health_daemon_support",
            "breezy.runtime.unit_health_daemons",
            "breezy.runtime.unit_health_dryrun",
            "breezy.runtime.unit_health_fold",
            "breezy.runtime.unit_health_intraday",
            "breezy.runtime.unit_health_journal",
            "breezy.runtime.unit_health_model",
            "breezy.runtime.unit_health_obs",
            "breezy.runtime.unit_health_rollup",
            "breezy.runtime.unit_health_store",
            "breezy.runtime.unit_health_support",
            "breezy.runtime.unit_health_types",
            "breezy.runtime.unit_health_verdict",
        ),
    }
)
