"""NWS data ingestion: transport, gating, integrity indexing and routing.

This facade curates the genuine cross-module public surface (identity
constants, data types, configs, exception taxonomies and stateless
factories/loaders); it deliberately omits raw clients (``HttpTransport``),
wire-shape helpers, and endpoint-specific internals. See each submodule for
the full implementation.

``gaps`` is intentionally NOT imported or re-exported here: it is a
separate, independently-owned module under active development.
"""

from breezy.ingest.config import (
    DEFAULT_DISCOVERY_MAX_BYTES,
    DEFAULT_DISCOVERY_MAX_DEPTH,
    DEFAULT_FINAL_DEADLINE_CHECK_INTERVAL_SECONDS,
    DEFAULT_PARSE_TIMEOUT_MS,
    DEFAULT_POLL_INTERVAL_SECONDS,
    NwsIngestActorConfig,
)
from breezy.ingest.gate import (
    DEFAULT_BURST_POLICY,
    DURABILITY_PROBE_KEY,
    ClosableStateStore,
    CrossSiteBurstPolicy,
    GateBlockedError,
    GateReason,
    GateState,
    GateStatus,
    InMemoryStateStore,
    SettlementGate,
    StateStore,
    StateStoreNotDurableError,
    StateStoreOpener,
    assert_state_store_durable,
)
from breezy.ingest.http import (
    DEFAULT_ACCEPT,
    DEFAULT_BASE_URL,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_MAX_BODY_BYTES,
    MAX_VALIDATOR_LENGTH,
    REDACTION_MARKER,
    USER_AGENT_ENV_VAR,
    ContentEncodingError,
    DecodeError,
    DisallowedHostError,
    FetchResult,
    ForbiddenError,
    InvalidCacheValidatorError,
    OversizeBodyError,
    ProxyEnvironmentError,
    RateLimitedError,
    RedirectError,
    ServerError,
    TransportError,
    TransportTimeoutError,
    UserAgentConfigurationError,
    redact_url,
)
from breezy.ingest.nws_envelope import (
    DEFAULT_MAX_GRAPH_ITEMS,
    DiscoveryEntry,
    NwsEnvelopeError,
    NwsEnvelopeFieldError,
    NwsEnvelopeStructureError,
    NwsEnvelopeTimestampError,
    NwsEnvelopeUuidError,
    ProductEnvelope,
    parse_discovery_list,
    parse_iso8601_to_ns,
    parse_product_envelope,
)
from breezy.ingest.product_index import (
    PRODUCT_INDEX_KEY_PREFIX,
    CorruptProductIndexEntryError,
    ProductIntegrityIndex,
    ProductIntegrityOutcome,
    ProductIntegrityResult,
)
from breezy.ingest.records import build_climate_day, build_raw_product
from breezy.ingest.routing import (
    INTEGRITY_ALARM_OUTCOMES,
    OUTCOME_SPECS,
    PARSE_ERROR_ROUTES,
    TRANSIENT_OUTCOMES,
    TRANSPORT_ERROR_ROUTES,
    GateAction,
    OutcomeSpec,
    PollOutcome,
    RouteDecision,
    Severity,
    WriteOutcomeLike,
    catalog_error_routes,
    route_catalog_error,
    route_fetch_result,
    route_parse_failure,
    route_sanity_violation,
    route_transport_error,
    route_unhandled_exception,
    route_write_outcome,
)
from breezy.ingest.shared_state import (
    DEFAULT_ALLOWED_HOSTS,
    FORBIDDEN_403_CAUSE,
    CrossSite403Window,
    DuplicateSharedIngestStateError,
    DuplicateSiteRegistrationError,
    ForeignComponentError,
    SharedIngestState,
    SharedIngestStateError,
    SiteSetError,
    UnknownSiteError,
)

__all__ = [
    "DEFAULT_ACCEPT",
    "DEFAULT_ALLOWED_HOSTS",
    "DEFAULT_BASE_URL",
    "DEFAULT_BURST_POLICY",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_DISCOVERY_MAX_BYTES",
    "DEFAULT_DISCOVERY_MAX_DEPTH",
    "DEFAULT_FINAL_DEADLINE_CHECK_INTERVAL_SECONDS",
    "DEFAULT_MAX_BODY_BYTES",
    "DEFAULT_MAX_GRAPH_ITEMS",
    "DEFAULT_PARSE_TIMEOUT_MS",
    "DEFAULT_POLL_INTERVAL_SECONDS",
    "DURABILITY_PROBE_KEY",
    "FORBIDDEN_403_CAUSE",
    "INTEGRITY_ALARM_OUTCOMES",
    "MAX_VALIDATOR_LENGTH",
    "OUTCOME_SPECS",
    "PARSE_ERROR_ROUTES",
    "PRODUCT_INDEX_KEY_PREFIX",
    "REDACTION_MARKER",
    "TRANSIENT_OUTCOMES",
    "TRANSPORT_ERROR_ROUTES",
    "USER_AGENT_ENV_VAR",
    "ClosableStateStore",
    "ContentEncodingError",
    "CorruptProductIndexEntryError",
    "CrossSite403Window",
    "CrossSiteBurstPolicy",
    "DecodeError",
    "DisallowedHostError",
    "DiscoveryEntry",
    "DuplicateSharedIngestStateError",
    "DuplicateSiteRegistrationError",
    "FetchResult",
    "ForbiddenError",
    "ForeignComponentError",
    "GateAction",
    "GateBlockedError",
    "GateReason",
    "GateState",
    "GateStatus",
    "InMemoryStateStore",
    "InvalidCacheValidatorError",
    "NwsEnvelopeError",
    "NwsEnvelopeFieldError",
    "NwsEnvelopeStructureError",
    "NwsEnvelopeTimestampError",
    "NwsEnvelopeUuidError",
    "NwsIngestActorConfig",
    "OutcomeSpec",
    "OversizeBodyError",
    "PollOutcome",
    "ProductEnvelope",
    "ProductIntegrityIndex",
    "ProductIntegrityOutcome",
    "ProductIntegrityResult",
    "ProxyEnvironmentError",
    "RateLimitedError",
    "RedirectError",
    "RouteDecision",
    "ServerError",
    "SettlementGate",
    "Severity",
    "SharedIngestState",
    "SharedIngestStateError",
    "SiteSetError",
    "StateStore",
    "StateStoreNotDurableError",
    "StateStoreOpener",
    "TransportError",
    "TransportTimeoutError",
    "UnknownSiteError",
    "UserAgentConfigurationError",
    "WriteOutcomeLike",
    "assert_state_store_durable",
    "build_climate_day",
    "build_raw_product",
    "catalog_error_routes",
    "parse_discovery_list",
    "parse_iso8601_to_ns",
    "parse_product_envelope",
    "redact_url",
    "route_catalog_error",
    "route_fetch_result",
    "route_parse_failure",
    "route_sanity_violation",
    "route_transport_error",
    "route_unhandled_exception",
    "route_write_outcome",
]
